### ISSUE TITLE
Advisor recommandation CCO Infra dashboard

### ISSUE THREAD

**Issue by cgeorgeot** [Azure/CCOInsights#250]
**Describe the feature you'd like**
In the tab "Azure Avisor" the fields Recommanded_SKU and DTU are empty (in Get Recommandations)

**Describe the solution you'd like**
It would be usefull to get these values in order to export a complete list with the VM or Databases with current are target SKU to rightsize them.

**Comment by Nickelodeon111** [comment]
If I refresh the table 'Get Recommendations', then 'Azure Advisor' page no longer shows the Security icon under the Category visual. The other 4 are not affected (HighAvailability, OperationalExcellence, Performance, Cost)

**Comment by Nickelodeon111** [comment]
In the Power BI template (CCOInfradashboard v9.1) the link for icons is: https://azure.github.io/ccodashboard/assets/2020_Icons/
If you browse any icon such as https://azure.github.io/ccodashboard/assets/2020_Icons/AdvisorSecurity.svg
you get error 404 , File Not found.

This URL gives the icons: https://github.com/Azure/CCOInsights/tree/master/docs/assets/2020_Icons/ ,
If you browse any icon: https://github.com/Azure/CCOInsights/blob/master/docs/assets/2020_Icons/AdvisorSecurity.svg ,
it displays the icon, but even if you use it in the Power BI template, you still don't get the image displayed. 

Once the issue is fixed, do I need to download a newer version of the Power BI template (CCOInfradashboard v9.1) or will a refresh fix it.

**Comment by josunefon** [comment]
Hi @Nickelodeon111 dou you mean this one? try to run it again because i donwloaded the last template and it's showing the correct data
![image](https://user-images.githubusercontent.com/39730064/180024781-cf05000c-ca5b-4183-a1bd-5469e62ce054.png)
![image](https://user-images.githubusercontent.com/39730064/180025196-21f6ac01-e9b1-4d99-8434-4dfa83d48855.png)


@cgeorgeot as I see, the API is not returning these fields anymore

![image](https://user-images.githubusercontent.com/39730064/180026022-b199b23d-94fc-4ac6-996f-7c6b78f505cf.png)

**Comment by cgeorgeot** [comment]
> 

Yes, it is exactly the case.
