### ISSUE TITLE
Unable to authenticate to management API with Tenant Reader

### ISSUE THREAD

**Issue by ToksHouston** [Azure/CCOInsights#299]
Unable to authenticate to management API with Tenant Reader
![image](https://user-images.githubusercontent.com/41170882/209177082-0b352606-74e5-4084-82d5-b9c57b98c172.png)
![image](https://user-images.githubusercontent.com/41170882/209177567-21689d25-43a5-4416-a902-0b1e7a6882a3.png)
<img width="186" alt="image" src="https://user-images.githubusercontent.com/41170882/209245348-a079200e-2c4b-443f-88b2-87368c0fbfbe.png">

**Comment by DrDonoso** [comment]
Hello, we are not storing the credentials for the CCO Connector, so everytime we refresh the dashboard credentials must be added.
Regarding the second login, you should use organizational account instead of anonymous login.
About the refresh, you should [modify privacy settings](https://github.com/azure/CCOInsights/wiki/Infrastructure-Dashboard-Deployment%20Guide#modify-privacy-settings) as referred in the wiki.
