### ISSUE TITLE
Not able to refresh report in Power BI service.

### ISSUE THREAD

**Issue by rajatbhamare** [Azure/CCOInsights#313]
I am getting a error when i try to refresh dataset in power BI service. 
Error Message:-

This dataset includes a dynamic data source. Since dynamic data sources aren't refreshed in the Power BI service, this dataset won't be refreshed. Learn more: https://aka.ms/dynamic-data-sources.
Data source for Query1
Data source for Query1
<img width="606" alt="Screenshot 2023-07-05 173846" src="https://github.com/Azure/CCOInsights/assets/121172598/697ef202-1552-4ec4-9548-9b77a2828a78">

**Comment by josunefon** [comment]
Hi @rajatbhamare, the current dashboard doesn't support Power BI Online. However, there's one solution that supports that in the  [early adopters backend branch](https://github.com/Azure/CCOInsights/tree/feature/EarlyAdopters_Backend)

**Comment by francesco1119** [comment]
None of the CCO dashboards can be refreshed? 
So what's the point then? 

There is no point to publish the dashboard if in 1 week time I'm showing outdated data. 
It's a pity that Microsoft, after all this work, cannot do the extra mile and create a refresh.

**Comment by francesco1119** [comment]
@josunefon , as you labelled this as "help wanted" I want to give you an help and find a way out. 

Do you think this scenario might be a valuable solution: 

1. Save the dashboard as a .pbix locally and setup a cron job that trigs a [Powershell script](https://community.fabric.microsoft.com/t5/Service/Automated-Refresh-of-Power-BI-Dataset-using-Powershell/m-p/1281325) that refresh the whole thing. 
2. Forcefully [refresh ](https://www.fourmoo.com/2018/06/05/using-the-power-bi-api-with-powershell-scripts-refreshing-your-dataset/)the data set (always with cron job)
3. Setting up a [refresh button](https://www.youtube.com/watch?v=7vCD8Zu686Q) within the dashboard
4. Power Automate [flow](https://data-marc.com/2020/01/13/manage-all-your-power-bi-refreshes-in-one-place-with-power-automate-flow/#:~:text=Power%20Automate%2C%20to%20trigger%20the,the%20Power%20BI%20REST%20API.)

Do you think some of these might work or are they all out of scope?

**Comment by josunefon** [comment]
Hi @francesco1119 ,

First and foremost, these dashboards (Governance and Infrastructure) use dynamic data sources, a feature not currently supported in Power BI Online at the time of dashboard development. Regrettably, the auto-refresh feature is unavailable due to technological limitations. Currently only directquery datasources and static endpoints are supported for [auto-refresh](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-automatic-page-refresh#authoring-reports-with-automatic-page-refresh-in-power-bi-desktop) ([table with supported methods](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-data#power-bi-refresh-types)). If you look at the [issues](https://github.com/Azure/CCOInsights/issues/151), this topic was already discussed.

Furthermore, within the early adopters_backend branch, efforts are underway to establish a static endpoint for storing all data extracted through API calls in an Azure-based storage. This initiative aims to enable the publication of the dashboard on Power BI Online, a capability already present in GitHub Contributions and Azure DevOps dashboards. 

So what's the point then? This is a tool that is being used by consultants worldwide to have a clear vision about what is the overall status of the governance and infrastructure in Azure when a project starts (Plug and play).

Feel free to contribute to this initiative with the scenario that you're proposing, your efforts will be appreciated.

**Comment by bmvalente** [comment]
@francesco1119 Just to clarify, as stated in the [Support](https://github.com/Azure/CCOInsights/blob/main/SUPPORT.md) document, this is community-based project that is maintained, on a **best effort basis**, by folks that happen to work at Microsoft. As mentioned by @josunefon, we are aware of the limitations that the current solution has, and we have been working on efforts to remove them or mitigate them. That work is not yet published in main (it still lives in its own branch) and we are working to make it public soon.
