### ISSUE TITLE
Loading pbit template no dialog for TenantName and AzureKind

### ISSUE THREAD

**Issue by Brianbla** [Azure/CCOInsights#328]
Working with a user that meets the requirements per the documentation.

When opening the Infrastructure or the Governance template, they are never prompted with the modal dialog for TenantName and AzureKind.

Is there a way to force that dialog to appear?

The user is logged on with their work account.

Thanks.

**Comment by josunefon** [comment]
Hi @Brianbla 

The .pbit file it will ask you always the input parameters because it contains just the schema and not the data, however, if you want to be 100% sure that the parameters will be always asked when you open the .pbit (and also in the .pbix file when you refresh) you can remove the credentials assigned to the data source following these steps:

- Go to Data source settings:
![image](https://github.com/Azure/CCOInsights/assets/39730064/25fac62a-8440-4181-99d1-3745636cf1f8)

- Clear all the permissions in current file and also the global permissions:
![image](https://github.com/Azure/CCOInsights/assets/39730064/3bf466e7-c603-4b06-ae7c-7c0f7d610066)

**Comment by brovoldt** [comment]
I was working with Brian on this issue and I don't have anything in the data source settings and that seems to be the problem its not connecting to my Azure Subscription but there doesn't seem to be an option for me to select the subscription
![image](https://github.com/Azure/CCOInsights/assets/50708660/8bce9bb1-3b4a-44d8-9f31-547ef51a44ed)

Is there a way to force the selection of the azure tenant or subscription to come up?

**Comment by brovoldt** [comment]
There is also nothing on the Global permission radio button 
![image](https://github.com/Azure/CCOInsights/assets/50708660/a62b663d-98dc-4710-9f4d-718d2bbac945)

**Comment by Brianbla** [comment]
@josunefon, many thanks for the prompt reply!

I tried that and it would never clear Connect CCO Dashboard... Which is not surprising as I don't think it is a permission but a message.

After clearing all permissions and closing the data source setting dialog nothing happens. Am I missing something?

On my company computer that is in Intune and on company VPN, things work as expected. On my other computer that is not domain joined or in Intune and not signed into PBI (I can't as it is not a company managed device) I can reproduce this user's issue.

Thank you for your time and attention.

**Comment by josunefon** [comment]
Hi @Brianbla if in your company computer works, there's nothing more we can do because probably this is related with the permissions you have ☹️

**Comment by bumbo73** [comment]
What I did was uninstall power bi and it worked for me. I tried to reset permissions and it would load the schema and ask it to refresh.
