### ISSUE TITLE
CCO Governance Dashboard Template GetPages error in Azure subscription provided by Visual Studio

### ISSUE THREAD

**Issue by fishingTX** [Azure/CCOInsights#338]
The "All Subscriptions" query doesn't work on a Visual Studio subscription.

**Comment by bmvalente** [comment]
This is to document the mail thread that we had on this topic.

- This issue is highlighted by an exception on "All Subscription > Get Pages" under the general purpose.
- The error is a path that it can't find, in the function code
```
= (Path)=>
let
     Source = Json.Document(Web.Contents(Path)),
     LL= @Source[value],
     result = try @LL & @GetPages(Source[#"nextLink"]) otherwise @LL
in
result
```

- We get this error in Azure Visual Studio subscriptions but not with regular Azure subscriptions
